// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Siriayanur/GoConcurrency/application"
	"github.com/Siriayanur/GoConcurrency/db"
)

// Injectors from wire.go:

func InitializeEvent() application.IApp {
	idb := db.NewDBInstance()
	iApp := application.NewApp(idb)
	return iApp
}
