# Start by giving a name to your workflow
name: Analyze branch

# then define on which event, here a push
on:
  push:
    # and the target with some regex to match our specific  branch names
    branches:
      - master
      - dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOPRIVATE: github.com/${{ github.repository_owner }}
  GONOSUMDB: github.com/${{ github.repository_owner }}
  REPORT_DIR: report
  VET_FILE: vet.txt
  COVERAGE_FILE: coverage.txt

# We can now build our job
jobs:
  analyse:
    runs-on: ['self-hosted', 'macOS', 'X64']

    steps:
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
        id: go
      - name: Add Go Path
        run: export PATH=$PATH:$(go env GOPATH)/bin

      # Another existing action, this one to checkout the repository
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      - name: Make report directory
        run: mkdir ${REPORT_DIR}

      - name: Test
        run: go test -short -race -cover -coverprofile=${REPORT_DIR}/${COVERAGE_FILE} -covermode=atomic -v ./... --tags=unit

      - name: Vet
        run: go vet -json ./... &> ${REPORT_DIR}/${VET_FILE}
    
      - name: Cleanup
        run: rm -rf ${REPORT_DIR}